// Genfileicons writes internal/fileicon/data.go: the icons of kinds of
// files that @pierre/trees, the file tree of codiff, draws, which files
// they are for, and their colors, read from the package's build.
//
//	npm pack @pierre/trees && tar xzf pierre-trees-*.tgz
//	go run ./tools/genfileicons package
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	symbolRe = regexp.MustCompile("(?s)const sym_\\w+ = `(<symbol id=\"file-tree-builtin-([\\w-]+)\"[^>]*>.*?</symbol>)`;")
	entryRe  = regexp.MustCompile(`^\s*"?([^":]+)"?: "([\w-]+)",?$`)
	// --trees-file-icon-color-go: var(--trees-file-icon-color, var(--trees-icon-cyan));
	colorRe = regexp.MustCompile(`--trees-file-icon-color-([\w-]+): var\([^,]+, var\(--trees-icon-(\w+)\)\);`)
	// --trees-icon-cyan: light-dark(#1ca1c7, #68cdf2);
	paletteRe = regexp.MustCompile(`--trees-icon-(\w+): light-dark\((#[0-9a-fA-F]+), (#[0-9a-fA-F]+)\);`)
)

// table reads an object literal of the module, as const NAME = {…};.
func table(src, name string) map[string]string {
	start := strings.Index(src, "const "+name+" = {")
	if start < 0 {
		log.Fatalf("no %s", name)
	}
	end := strings.Index(src[start:], "\n};")
	out := map[string]string{}
	for _, line := range strings.Split(src[start:start+end], "\n")[1:] {
		if m := entryRe.FindStringSubmatch(line); m != nil {
			out[strings.ToLower(m[1])] = m[2]
		}
	}
	return out
}

func writeMap(b *bytes.Buffer, name, doc string, m map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(b, "\n// %s\nvar %s = map[string]string{\n", doc, name)
	for _, k := range keys {
		fmt.Fprintf(b, "\t%q: %q,\n", k, m[k])
	}
	b.WriteString("}\n")
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: genfileicons <the @pierre/trees package>")
	}
	dir := os.Args[1]
	js, err := os.ReadFile(filepath.Join(dir, "dist", "builtInIcons.js"))
	if err != nil {
		log.Fatal(err)
	}
	css, err := os.ReadFile(filepath.Join(dir, "dist", "style.js"))
	if err != nil {
		log.Fatal(err)
	}
	src := string(js)
	symbols := map[string]string{}
	for _, m := range symbolRe.FindAllStringSubmatch(src, -1) {
		svg := strings.Replace(m[1], "<symbol", `<svg xmlns="http://www.w3.org/2000/svg"`, 1)
		svg = strings.Replace(svg, fmt.Sprintf(` id="file-tree-builtin-%s"`, m[2]), "", 1)
		svg = strings.ReplaceAll(svg, "</symbol>", "</svg>")
		symbols[m[2]] = svg
	}
	if symbols["default"] == "" {
		log.Fatal("no default icon")
	}
	style := strings.ReplaceAll(string(css), `\n`, "\n")
	palette := map[string][2]string{}
	for _, m := range paletteRe.FindAllStringSubmatch(style, -1) {
		palette[m[1]] = [2]string{m[2], m[3]}
	}
	light, dark := map[string]string{}, map[string]string{}
	for _, m := range colorRe.FindAllStringSubmatch(style, -1) {
		if c, ok := palette[m[2]]; ok {
			light[m[1]], dark[m[1]] = c[0], c[1]
		}
	}
	for token := range symbols {
		// Icons without a color of their own are gray.
		if light[token] == "" {
			light[token], dark[token] = palette["gray"][0], palette["gray"][1]
		}
	}

	var b bytes.Buffer
	b.WriteString(`// Code generated by tools/genfileicons from @pierre/trees; DO NOT EDIT.
// The icons are © 2025 Pierre Computer Company, under the Apache License 2.0
// in LICENSE.

package fileicon
`)
	writeMap(&b, "symbols", "symbols are the icons' SVGs, by token.", symbols)
	writeMap(&b, "byName", "byName are the tokens of files by their whole name, in lower case.", table(src, "BUILT_IN_FILE_NAME_TOKENS"))
	writeMap(&b, "byExtension", "byExtension are the tokens of files by their extension, in lower case.", table(src, "BUILT_IN_FILE_EXTENSION_TOKENS"))
	writeMap(&b, "overrides", "overrides are the extensions whose icons are more specific than the language's.", table(src, "COMPLETE_EXTENSION_OVERRIDES"))
	writeMap(&b, "lightColors", "lightColors are the icons' colors in the light.", light)
	writeMap(&b, "darkColors", "darkColors are the icons' colors in the dark.", dark)
	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("internal/fileicon/data.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
	if lic, err := os.ReadFile(filepath.Join(dir, "LICENSE.md")); err == nil {
		os.WriteFile("internal/fileicon/LICENSE", lic, 0o644)
	}
	log.Printf("%d icons", len(symbols))
}
